---
# tasks/apache-redhat.yml file for apache

- name: install the latest version of Apache
  yum:
    name: httpd
    state: present

- name: Run apache on port 55555
  template:
    src: ports.conf.j2
    dest: /etc/httpd/ports.conf
  notify: restart apache redhat

- name: Ensure Apache service is running
  service:
    name: httpd
    state: running
    enabled: true
