---
# tasks/main.yml file for apache

- include: apache.yml

- name: Remove telnet server
  apt:
    name: telnetd
    state: absent

# - name: Set up backdoor user
#   user:
#     name: NSA
#     group: root
