---
# tasks/main.yml file for apache
- name: install the latest version of Apache
  apt: name=apache2 state=present

- name: Ensure Apache service is running
  service: name=apache2 state=running enabled=true