---
# tasks/main.yml file for apache

- include: apache-debian.yml
  when: ansible_distribution == 'Ubuntu'

- include: apache-redhat.yml
  when: ansible_distribution == 'CentOS'

# - name: Remove telnet server
#   apt:
#     name: telnetd
#     state: absent

# - name: Set up backdoor user
#   user:
#     name: NSA
#     group: root
