---
driver:
  name: docker
  binary: /usr/local/bin/docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  roles_path: ../..
  require_ruby_for_busser: true

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: edmundd:ubuntu-14.04
      platform: ubuntu
  # - name: ubuntu-15.04
  #   driver_config:
  #     image: edmundd:ubuntu-15.04
  #     platform: ubuntu
  # - name: centos-7
  #   driver_config:
  #     image: edmundd:centos-7
  #     platform: centos

suites:
  - name: default

verifier:
  ruby_bindir: '/usr/bin'
